name: Automatic Releases

on: push

jobs:
  release:

    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
      pull-requests: "read"

    steps:
      - uses: actions/checkout@v3
      - name: Set up WIN JDK 17
        uses: oracle-actions/setup-java@v1
        with:
          uri: https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip
    
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github

      - name: Build with Maven
        run: mvn package assembly:single

      - name: Delete Package
        run: |
          curl --request DELETE \
          --url https://api.github.com/user/packages/maven/com.monique.mailer-core \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28'

      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>moniq-e</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy
